name: zentratek-fac2csv

services:
  - name: web
    github:
      repo: zentratek/zentratek-fac2csv
      branch: main
      deploy_on_push: true

    environment_slug: python

    envs:
      - key: FLASK_ENV
        value: production

    run_command: gunicorn --workers 2 --threads 4 --worker-class=gthread --timeout 120 --bind :8080 --access-logfile - --error-logfile - wsgi:app

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs
