name: zentratek-fac2csv

services:
  - name: web
    github:
      repo: zentratek/zentratek-fac2csv
      branch: main
      deploy_on_push: true

    environment_slug: python

    envs:
      - key: FLASK_ENV
        value: production

    run_command: gunicorn --bind :8080 --workers 2 --threads 4 --timeout 120 app:app

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs
